---
- name: copy apache config file to remote server
  copy:
    src: /home/ubuntu/ansible/apache.conf
    dest: /etc/apache2/sites-available/apache.conf
    owner: "www-data"
    group: "www-data"
    mode: '0644'
      

    # execute some shell commands to enable the new host in Apache2.
    # use the pipe operator ‘shell: |’ to be able to run multiple commands.
- name: enable the new config
  shell: |
    a2ensite apache.conf
    a2dissite 000-default.conf
    a2enmod rewrite
    service apache2 restart

