---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip', 'php-common', 'php-imagick', 'php-cli', 'php-dev', 'php-imap', 'php-opcache' ]


#MySQL Settings
mysql_root_password: "1234"
mysql_db: "laravel"
mysql_user: "root"
mysql_password: "1234"

#HTTP Settings
http_host: "your_domain"
http_conf: "apache.conf"
http_port: "80"
clone_name: "Laravel"
